### ISSUE TITLE
add some sort of cacheing for vocabulary, so it won't get reloaded unnecessarily 

### ISSUE THREAD

**Issue by jonathanbratt** [jonathanbratt/wordpiece#4]
summary of slack conversation with @jonthegeek :
maybe have a parameter in the load_vocab function that permits the following behavior:
 1. look in a canonical place (e.g. in directory alongside vocab.txt) (or controlled by option?) for a cached result to return
 2. save result to cache in canonical place

**Comment by jonthegeek** [comment]
To expand on this a little:
* When a vocab loads, there's enough processing that it's slow enough that I could imagine it making a difference for something that gets called a lot (loading the file, trimming whitespace, converting to unicode, setting up the named vector, and inferring casedness).
* Save that as something lightweight. Probably RDS so we don't need another dependency.
* Since it's saving, add an option that controls that behavior (it's rude to have a non-optional side effect like that).
* Noodle a bit on WHERE to save. The user might not have write access to the same dir as the vocab. I guess we can probably just ask. Using the rappdirs rules probably wouldn't hurt.
* I originally thought we'd use original_filename.rds for the filename, but we might want to hash the path or something to make SURE it will be unique for different vocabs? Or, hmm, could we hash the vocabulary itself, so the filename would be the same if the vocab is the same? That feels possible and kinda awesome...

**Comment by jonthegeek** [comment]
Er duh it has to be obvious from the filename where to look for the cache, so hashing the CONTENTS of the file probably wastes time. Hashing the path is probably the best option?
